// lib/firebase_options.dart
// ------------------------------------------------------
// 🔥 FIREBASE OPTIONS (TEMPLATE)
// ------------------------------------------------------
// ⚠️ CHÚ Ý: File này là TEMPLATE
// Bạn cần chạy lệnh sau để tạo file thật:
//
//   flutterfire configure
//
// Lệnh trên sẽ tự động tạo file này với cấu hình Firebase
// của bạn cho tất cả các platforms (Android, iOS, Web, etc.)
// ------------------------------------------------------

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC142_gS6BA7leHbCGVoByFmkluYBVuYZg',
    appId: '1:122921125037:web:b555c903061e2d00f33224',
    messagingSenderId: '122921125037',
    projectId: 'flutter-travel-review',
    authDomain: 'flutter-travel-review.firebaseapp.com',
    storageBucket: 'flutter-travel-review.firebasestorage.app',
  );

  // ⚠️ PLACEHOLDER - Chạy 'flutterfire configure' để tạo config thật

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtBX6e2vBZ8R1dsKxxqxyZoNwYbqNHsAs',
    appId: '1:122921125037:android:3b0123ee60d40f5ff33224',
    messagingSenderId: '122921125037',
    projectId: 'flutter-travel-review',
    storageBucket: 'flutter-travel-review.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM29MWb6qrRWAq0yptTtjeNJfOJuv-rus',
    appId: '1:122921125037:ios:12e18771fa5ff63cf33224',
    messagingSenderId: '122921125037',
    projectId: 'flutter-travel-review',
    storageBucket: 'flutter-travel-review.firebasestorage.app',
    iosBundleId: 'com.example.flutterTravelReview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM29MWb6qrRWAq0yptTtjeNJfOJuv-rus',
    appId: '1:122921125037:ios:12e18771fa5ff63cf33224',
    messagingSenderId: '122921125037',
    projectId: 'flutter-travel-review',
    storageBucket: 'flutter-travel-review.firebasestorage.app',
    iosBundleId: 'com.example.flutterTravelReview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC142_gS6BA7leHbCGVoByFmkluYBVuYZg',
    appId: '1:122921125037:web:97bbcdf46c3afd11f33224',
    messagingSenderId: '122921125037',
    projectId: 'flutter-travel-review',
    authDomain: 'flutter-travel-review.firebaseapp.com',
    storageBucket: 'flutter-travel-review.firebasestorage.app',
  );

}